// lib/clasicos-curados.ts
import { VideoTecnica } from './types'

export interface EjercicioCatalogo extends VideoTecnica {
  exerciseId: string
  nombreIngles?: string
  equipo: string
  musculosPrincipales: string[]
  musculosSecundarios?: string[]
  instruccionesPasoAPaso: string[]
}

// ── Ejercicios clásicos traducidos y destacados del gimnasio ─────────────────
export const CLASICOS_CURADOS: EjercicioCatalogo[] = [
  // PECHO
  {
    id: 'cat-pecho-1',
    exerciseId: 'EIeI8Vf',
    titulo: 'Press de Banca Plano con Barra',
    nombreIngles: 'Barbell Bench Press',
    grupoMuscular: 'Pecho',
    duracion: 'Loop GIF',
    formato: 'GIF',
    nivel: 'Técnica estricta',
    equipo: 'Barra',
    videoUrl: 'https://static.exercisedb.dev/media/EIeI8Vf.gif',
    gifUrl: 'https://static.exercisedb.dev/media/EIeI8Vf.gif',
    descripcion: 'Ejercicio fundamental para pectoral mayor, deltoides anterior y tríceps.',
    musculosPrincipales: ['Pectoral mayor', 'Tríceps braquial'],
    musculosSecundarios: ['Deltoides anterior', 'Core'],
    consejosClave: [
      'Retracción escapular firme contra el banco.',
      'Bajá la barra a la altura del esternón con codos a 45°-60°.',
      'Empujá con los pies contra el suelo (leg drive).',
    ],
    instruccionesPasoAPaso: [
      'Acostate en el banco con los ojos alineados con la barra.',
      'Tomá la barra con agarre ligeramente más ancho que los hombros.',
      'Descendé controladamente hasta rozar el esternón.',
      'Empujá con potencia exhalando hasta extender los brazos.',
    ],
  },
  {
    id: 'cat-pecho-2',
    exerciseId: 'ns0SIbU',
    titulo: 'Press Inclinado con Mancuernas',
    nombreIngles: 'Dumbbell Incline Bench Press',
    grupoMuscular: 'Pecho',
    duracion: 'Loop GIF',
    formato: 'GIF',
    nivel: 'Hipertrofia',
    equipo: 'Mancuerna',
    videoUrl: 'https://static.exercisedb.dev/media/ns0SIbU.gif',
    gifUrl: 'https://static.exercisedb.dev/media/ns0SIbU.gif',
    descripcion: 'Enfocado en el haz clavicular (pectoral superior) con gran rango de movimiento.',
    musculosPrincipales: ['Pectoral superior (clavicular)'],
    musculosSecundarios: ['Deltoides anterior', 'Tríceps'],
    consejosClave: [
      'Ajustá el banco entre 30° y 45°.',
      'No choques las mancuernas arriba para mantener tensión constante.',
    ],
    instruccionesPasoAPaso: [
      'Sentate con mancuernas en los muslos e impulsalas al acostarte.',
      'Bajá sintiendo el estiramiento del pectoral superior.',
      'Empujá de forma convergente hacia arriba.',
    ],
  },
  {
    id: 'cat-pecho-3',
    exerciseId: 'WcHl7ru',
    titulo: 'Press de Banca Agarre Cerrado',
    nombreIngles: 'Close-Grip Bench Press',
    grupoMuscular: 'Pecho',
    duracion: 'Loop GIF',
    formato: 'GIF',
    nivel: 'Fuerza',
    equipo: 'Barra',
    videoUrl: 'https://static.exercisedb.dev/media/WcHl7ru.gif',
    gifUrl: 'https://static.exercisedb.dev/media/WcHl7ru.gif',
    descripcion: 'Empuje que focaliza la porción esternal y la cabeza lateral del tríceps.',
    musculosPrincipales: ['Pectoral medio', 'Tríceps'],
    musculosSecundarios: ['Hombros'],
    consejosClave: ['Agarre al ancho de hombros, codos pegados al cuerpo.'],
    instruccionesPasoAPaso: ['Descendé la barra hacia el pecho bajo y empujá con tríceps.'],
  },

  // ESPALDA
  {
    id: 'cat-espalda-1',
    exerciseId: 'qdRxqCj',
    titulo: 'Jalón al Pecho en Polea Alta',
    nombreIngles: 'Cable Lat Pulldown',
    grupoMuscular: 'Espalda',
    duracion: 'Loop GIF',
    formato: 'GIF',
    nivel: 'Técnica estricta',
    equipo: 'Polea',
    videoUrl: 'https://static.exercisedb.dev/media/qdRxqCj.gif',
    gifUrl: 'https://static.exercisedb.dev/media/qdRxqCj.gif',
    descripcion: 'Clásico para amplitud y densidad del dorsal ancho.',
    musculosPrincipales: ['Dorsal ancho', 'Redondo mayor'],
    musculosSecundarios: ['Bíceps braquial'],
    consejosClave: ['Tirá pensando en llevar los codos hacia abajo y atrás.'],
    instruccionesPasoAPaso: ['Llevá la barra a la parte alta del esternón y controlá el retorno.'],
  },
  {
    id: 'cat-espalda-2',
    exerciseId: 'ila4NZS',
    titulo: 'Peso Muerto Tradicional con Barra',
    nombreIngles: 'Barbell Deadlift',
    grupoMuscular: 'Espalda',
    duracion: 'Loop GIF',
    formato: 'GIF',
    nivel: 'Fuerza básica',
    equipo: 'Barra',
    videoUrl: 'https://static.exercisedb.dev/media/ila4NZS.gif',
    gifUrl: 'https://static.exercisedb.dev/media/ila4NZS.gif',
    descripcion: 'Levantamiento definitivo de cadena posterior completa.',
    musculosPrincipales: ['Erectores espinales', 'Dorsales', 'Glúteos'],
    musculosSecundarios: ['Isquiosurales', 'Trapecios'],
    consejosClave: ['Barra pegada a las piernas, columna neutra en todo momento.'],
    instruccionesPasoAPaso: ['Levantá empujando el piso con las piernas y extendé la cadera.'],
  },
  {
    id: 'cat-espalda-3',
    exerciseId: 'wQ2c4XD',
    titulo: 'Peso Muerto Rumano con Barra',
    nombreIngles: 'Barbell Romanian Deadlift',
    grupoMuscular: 'Espalda',
    duracion: 'Loop GIF',
    formato: 'GIF',
    nivel: 'Hipertrofia',
    equipo: 'Barra',
    videoUrl: 'https://static.exercisedb.dev/media/wQ2c4XD.gif',
    gifUrl: 'https://static.exercisedb.dev/media/wQ2c4XD.gif',
    descripcion: 'Bisagra de cadera pura para isquiotibiales y glúteos.',
    musculosPrincipales: ['Isquiotibiales', 'Glúteo mayor'],
    musculosSecundarios: ['Lumbares'],
    consejosClave: ['Empujá la cadera hacia atrás con rodillas semirrígidas.'],
    instruccionesPasoAPaso: ['Deslizá la barra por los muslos y apretá glúteos para subir.'],
  },

  // PIERNAS
  {
    id: 'cat-piernas-1',
    exerciseId: 'DhMl549',
    titulo: 'Sentadilla Libre con Barra Trasera',
    nombreIngles: 'Barbell Back Squat',
    grupoMuscular: 'Piernas',
    duracion: 'Loop GIF',
    formato: 'GIF',
    nivel: 'Biomecánica',
    equipo: 'Barra',
    videoUrl: 'https://static.exercisedb.dev/media/DhMl549.gif',
    gifUrl: 'https://static.exercisedb.dev/media/DhMl549.gif',
    descripcion: 'Ejercicio fundamental de tren inferior para cuádriceps y glúteos.',
    musculosPrincipales: ['Cuádriceps', 'Glúteo mayor'],
    musculosSecundarios: ['Core', 'Aductores'],
    consejosClave: ['Rodillas en dirección de las puntas de los pies, profundidad paralela.'],
    instruccionesPasoAPaso: ['Descendé flexionando rodillas y cadera, y subí empujando el suelo.'],
  },
  {
    id: 'cat-piernas-2',
    exerciseId: 'yn2lLSI',
    titulo: 'Prensa de Piernas a 45°',
    nombreIngles: 'Sled 45° Leg Press',
    grupoMuscular: 'Piernas',
    duracion: 'Loop GIF',
    formato: 'GIF',
    nivel: 'Hipertrofia',
    equipo: 'Máquina',
    videoUrl: 'https://static.exercisedb.dev/media/yn2lLSI.gif',
    gifUrl: 'https://static.exercisedb.dev/media/yn2lLSI.gif',
    descripcion: 'Sobrecarga en cuádriceps y glúteos con apoyo lumbar.',
    musculosPrincipales: ['Cuádriceps', 'Glúteos'],
    musculosSecundarios: ['Isquiosurales'],
    consejosClave: ['No despegues la zona lumbar del respaldo en el punto profundo.'],
    instruccionesPasoAPaso: ['Flexioná rodillas a 90° y empujá desde los talones.'],
  },
  {
    id: 'cat-piernas-3',
    exerciseId: '17lJ1kr',
    titulo: 'Camilla Femoral Tumbado',
    nombreIngles: 'Lying Leg Curl',
    grupoMuscular: 'Piernas',
    duracion: 'Loop GIF',
    formato: 'GIF',
    nivel: 'Aislamiento',
    equipo: 'Máquina',
    videoUrl: 'https://static.exercisedb.dev/media/17lJ1kr.gif',
    gifUrl: 'https://static.exercisedb.dev/media/17lJ1kr.gif',
    descripcion: 'Aislamiento de flexión de rodilla para isquiotibiales.',
    musculosPrincipales: ['Isquiotibiales'],
    musculosSecundarios: ['Gemelos'],
    consejosClave: ['Pelvis pegada al banco, bajada controlada en 2 segundos.'],
    instruccionesPasoAPaso: ['Flexioná piernas llevando talones hacia los glúteos.'],
  },

  // HOMBROS
  {
    id: 'cat-hombros-1',
    exerciseId: 'DsgkuIt',
    titulo: 'Elevaciones Laterales con Mancuernas',
    nombreIngles: 'Dumbbell Lateral Raise',
    grupoMuscular: 'Hombros',
    duracion: 'Loop GIF',
    formato: 'GIF',
    nivel: 'Aislamiento',
    equipo: 'Mancuerna',
    videoUrl: 'https://static.exercisedb.dev/media/DsgkuIt.gif',
    gifUrl: 'https://static.exercisedb.dev/media/DsgkuIt.gif',
    descripcion: 'Aislamiento de la cabeza lateral del deltoides para dar amplitud.',
    musculosPrincipales: ['Deltoides lateral'],
    musculosSecundarios: ['Trapecios'],
    consejosClave: ['Elevá en el plano escapular con codos semiflexionados.'],
    instruccionesPasoAPaso: ['Subí hasta la altura de los hombros y resistí la bajada.'],
  },
  {
    id: 'cat-hombros-2',
    exerciseId: 'bBi35y3',
    titulo: 'Press de Hombros con Mancuernas',
    nombreIngles: 'Dumbbell Shoulder Press',
    grupoMuscular: 'Hombros',
    duracion: 'Loop GIF',
    formato: 'GIF',
    nivel: 'Fuerza básica',
    equipo: 'Mancuerna',
    videoUrl: 'https://static.exercisedb.dev/media/bBi35y3.gif',
    gifUrl: 'https://static.exercisedb.dev/media/bBi35y3.gif',
    descripcion: 'Empuje vertical para hombros completos y tríceps.',
    musculosPrincipales: ['Deltoides anterior', 'Deltoides lateral'],
    musculosSecundarios: ['Tríceps'],
    consejosClave: ['Codos ligeramente al frente a 60°, abdomen firme.'],
    instruccionesPasoAPaso: ['Empujá hacia arriba verticalmente y controlá el descenso.'],
  },

  // BRAZOS
  {
    id: 'cat-brazos-1',
    exerciseId: '6TG6x2w',
    titulo: 'Curl de Bíceps con Barra EZ',
    nombreIngles: 'EZ Barbell Curl',
    grupoMuscular: 'Brazos',
    duracion: 'Loop GIF',
    formato: 'GIF',
    nivel: 'Técnica estricta',
    equipo: 'Barra',
    videoUrl: 'https://static.exercisedb.dev/media/6TG6x2w.gif',
    gifUrl: 'https://static.exercisedb.dev/media/6TG6x2w.gif',
    descripcion: 'Agarre ergonómico semi-supino para desarrollo de bíceps.',
    musculosPrincipales: ['Bíceps braquial'],
    musculosSecundarios: ['Braquial anterior'],
    consejosClave: ['Codos pegados al cuerpo, sin balanceo de espalda.'],
    instruccionesPasoAPaso: ['Flexioná los codos elevando la barra y apretá arriba 1 seg.'],
  },
  {
    id: 'cat-brazos-2',
    exerciseId: 'GNhAeJ0',
    titulo: 'Curl Martillo con Mancuernas',
    nombreIngles: 'Dumbbell Hammer Curl',
    grupoMuscular: 'Brazos',
    duracion: 'Loop GIF',
    formato: 'GIF',
    nivel: 'Aislamiento',
    equipo: 'Mancuerna',
    videoUrl: 'https://static.exercisedb.dev/media/GNhAeJ0.gif',
    gifUrl: 'https://static.exercisedb.dev/media/GNhAeJ0.gif',
    descripcion: 'Agarre neutro para braquial y antebrazos.',
    musculosPrincipales: ['Braquial', 'Braquiorradial'],
    musculosSecundarios: ['Bíceps'],
    consejosClave: ['Palmas enfrentadas durante todo el recorrido.'],
    instruccionesPasoAPaso: ['Elevá las mancuernas manteniendo las palmas paralelas.'],
  },
  {
    id: 'cat-brazos-3',
    exerciseId: '3ZflifB',
    titulo: 'Extensiones de Tríceps en Polea',
    nombreIngles: 'Cable Triceps Pushdown',
    grupoMuscular: 'Brazos',
    duracion: 'Loop GIF',
    formato: 'GIF',
    nivel: 'Aislamiento',
    equipo: 'Polea',
    videoUrl: 'https://static.exercisedb.dev/media/3ZflifB.gif',
    gifUrl: 'https://static.exercisedb.dev/media/3ZflifB.gif',
    descripcion: 'Aislamiento directo de tríceps en polea alta.',
    musculosPrincipales: ['Tríceps braquial'],
    musculosSecundarios: ['Antebrazos'],
    consejosClave: ['Codos fijos a los costados, extensión total abajo.'],
    instruccionesPasoAPaso: ['Empujá hacia abajo hasta trabar la extensión de codos.'],
  },

  // CORE
  {
    id: 'cat-core-1',
    exerciseId: 'VBAWRPG',
    titulo: 'Plancha Abdominal Isométrica',
    nombreIngles: 'Front Plank',
    grupoMuscular: 'Core',
    duracion: 'Loop GIF',
    formato: 'GIF',
    nivel: 'Básico',
    equipo: 'Peso corporal',
    videoUrl: 'https://static.exercisedb.dev/media/VBAWRPG.gif',
    gifUrl: 'https://static.exercisedb.dev/media/VBAWRPG.gif',
    descripcion: 'Estabilidad antiextensión para todo el cinturón abdominal.',
    musculosPrincipales: ['Recto abdominal', 'Transverso'],
    musculosSecundarios: ['Glúteos'],
    consejosClave: ['Cuerpo en línea recta de cabeza a talones, glúteos contraídos.'],
    instruccionesPasoAPaso: ['Apoyate sobre antebrazos y puntas de pies manteniendo tensión.'],
  },
  {
    id: 'cat-core-2',
    exerciseId: 'I3tsCnC',
    titulo: 'Elevación de Piernas Colgado',
    nombreIngles: 'Hanging Leg Raise',
    grupoMuscular: 'Core',
    duracion: 'Loop GIF',
    formato: 'GIF',
    nivel: 'Avanzado',
    equipo: 'Peso corporal',
    videoUrl: 'https://static.exercisedb.dev/media/I3tsCnC.gif',
    gifUrl: 'https://static.exercisedb.dev/media/I3tsCnC.gif',
    descripcion: 'Máxima activación para porción inferior del abdomen.',
    musculosPrincipales: ['Recto abdominal inferior'],
    musculosSecundarios: ['Flexores de cadera'],
    consejosClave: ['Enrollá la pelvis hacia el pecho, evitá el balanceo.'],
    instruccionesPasoAPaso: ['Colgate de una barra y elevá las piernas contrayendo el abdomen.'],
  },
]
